### ISSUE TITLE
Update & improve README.md

### ISSUE THREAD

**Issue by mhoff** [team-pltb/pltb-eval#3]

**Comment by mhoff** [comment]
I think the README should now suffice. Review pls.

**Comment by stefanorf** [comment]
I did the review and changed some things. Please have a final look on my changes. And please read the last sentence, I don't really get it, if it is correct. After that, you can close this Issue.

**Comment by mhoff** [comment]
With change you refer to the inclusion of license information and the README in res/datasets?
I think this README should be included in the general README.md as a subsection.
Last sentence in README.md? Which one do you mean? "To generate the histogram plots execute the following commands:"?

**Comment by stefanorf** [comment]
Nevermind, I mistakenly answered to this issue instead of issue #1 in the repository pltb.

**Comment by stefanorf** [comment]
I did review the evaluation part of README.md in the repository pltb. If you agree you can close this issue.

**Comment by mhoff** [comment]
@stefanorf "out of the precomputed results" or "using the precomputed results"?
Choose what suits you better. Closed.
