### ISSUE TITLE
PLTB integration

### ISSUE THREAD

**Issue by mhoff** [team-pltb/pltb-eval#4]
At the moment this repository has no connection to the repository which bears the pltb binary we require (for one script at least).
Is such a connection necessary? If so, would the inclusion of pltb as a submodule suffice?
Can't we assume pltb to be on the path?
Or should we supply the binary via command line or environment variables?
We could also integrate this repository as an 'eval' subfolder in the pltb repository.
But this would also require implicit addressing of the pltb binary via '../pltb'.
What do you say?

**Comment by stamatak** [comment]
I'd put this as a subfolder into the pltb repository and then call ./pltb, maybe not most elegant, but probably the fastest way of doing it for people who want to test all this.

alexis

**Comment by mhoff** [comment]
Indeed. The problem I see is that people could get confused about the working directory.
Your solution suggests that one has to call the scripts like './eval/calculate...'.
That means without extra logic everything breaks if one does call it from within the 'eval' folder.

The overall solution I see is to do it that way and to check for the existence of the pltb binary.
This should suffice.
Agreed?

Michael

**Comment by mhoff** [comment]
I have now integrated pltb-eval into pltb as a subfolder.
@team-pltb/owners please do not commit to the pltb-eval repository anymore. we will finish remaining issues and then delete the whole repo.
